# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the issue template!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request! please wait for maintainer to approve your PR...
  ![please wait](https://github.com/shreeshailaya/C-DAC-Notes/blob/main/Media/please-wait-gif.gif)

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request!
  Thank you for your valuable Contribution.
  please fill out the following form for further reference.
  https://forms.gle/F6vkGHBCVNLvVBsm8
  ![proud](https://github.com/shreeshailaya/C-DAC-Notes/blob/main/Media/proud_of.gif)